apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-afpsuvnp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-afpsuvnp 
  name: go-afpsuvnp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-afpsuvnp
    weight: 100 
